theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-uga.svg"